name: Tests

on:
  push:
    paths-ignore:
      - '**.md'
      - 'docs/**'
    branches:
      - '**'
  pull_request:
    types: [ready_for_review, synchronize, opened]
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        php: [8.1, 8.2, 8.3]
        laravel: ['^10.0', '^11.0']
        include:
          - laravel: ^10.0
            testbench: ^8.0
          - laravel: ^11.0
            testbench: ^9.0
        exclude:
          - php: 8.1
            laravel: '^11.0'
    name: PHP${{ matrix.php }} - Laravel${{ matrix.laravel }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, fileinfo, pdo_sqlite, iconv
          tools: composer:v2
          coverage: xdebug

      - name: Check Composer configuration
        run: composer validate --strict

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-

      - name: Install dependencies from composer.json
        run: composer update --with='laravel/framework:${{ matrix.laravel }}' --with='orchestra/testbench:${{ matrix.testbench }}' --no-interaction --no-progress

      - name: Check PSR-4 mapping
        run: composer dump-autoload --optimize --strict-psr

      - name: Execute tests
        run: |
          ls -alh workbench/database/migrations
          composer test
